use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .get_connection()
            .execute_unprepared(
                r#"
                ALTER TABLE users
                    ADD COLUMN IF NOT EXISTS media_bytes_reserved bigint NOT NULL DEFAULT 0;

                CREATE TABLE IF NOT EXISTS notebook_media_blobs (
                    id text PRIMARY KEY,
                    user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    content_hash text,
                    object_key text NOT NULL UNIQUE,
                    state text NOT NULL DEFAULT 'uploading',
                    content_type text NOT NULL,
                    media_type text NOT NULL,
                    format text NOT NULL,
                    bytes bigint NOT NULL,
                    width bigint NOT NULL DEFAULT 0,
                    height bigint NOT NULL DEFAULT 0,
                    duration_seconds double precision NOT NULL DEFAULT 0,
                    checksum_sha256 text NOT NULL,
                    etag text,
                    derivative_key text,
                    derivative_bytes bigint NOT NULL DEFAULT 0,
                    quota_counted boolean NOT NULL DEFAULT false,
                    upload_expires_at timestamptz,
                    delete_after timestamptz,
                    lease_owner text,
                    leased_at timestamptz,
                    attempt_count integer NOT NULL DEFAULT 0,
                    last_error_code text,
                    created_at timestamptz NOT NULL DEFAULT now(),
                    updated_at timestamptz NOT NULL DEFAULT now(),
                    CONSTRAINT notebook_media_blobs_state_check CHECK (
                        state = ANY (ARRAY['uploading','ready','gc_pending','deleting','failed'])
                    ),
                    CONSTRAINT notebook_media_blobs_bytes_check CHECK (bytes >= 0),
                    CONSTRAINT notebook_media_blobs_derivative_bytes_check CHECK (derivative_bytes >= 0)
                );

                CREATE TABLE IF NOT EXISTS notebook_media_references (
                    id text PRIMARY KEY,
                    blob_id text NOT NULL REFERENCES notebook_media_blobs(id) ON DELETE RESTRICT,
                    user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    workspace_id text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
                    note_id text NOT NULL REFERENCES notebook_notes(id) ON DELETE CASCADE,
                    original_filename text NOT NULL,
                    provisional_until timestamptz,
                    created_at timestamptz NOT NULL DEFAULT now(),
                    CONSTRAINT notebook_media_references_note_blob_key UNIQUE (note_id, blob_id)
                );

                CREATE TABLE IF NOT EXISTS notebook_media_uploads (
                    id text PRIMARY KEY,
                    blob_id text NOT NULL REFERENCES notebook_media_blobs(id) ON DELETE CASCADE,
                    user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    workspace_id text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
                    note_id text NOT NULL REFERENCES notebook_notes(id) ON DELETE CASCADE,
                    idempotency_key text NOT NULL,
                    expected_hash text NOT NULL,
                    expected_bytes bigint NOT NULL,
                    reserved_bytes bigint NOT NULL DEFAULT 0,
                    content_type text NOT NULL,
                    original_filename text NOT NULL,
                    state text NOT NULL DEFAULT 'uploading',
                    multipart_upload_id text,
                    multipart_parts jsonb NOT NULL DEFAULT '[]'::jsonb,
                    error_code text,
                    expires_at timestamptz NOT NULL,
                    created_at timestamptz NOT NULL DEFAULT now(),
                    updated_at timestamptz NOT NULL DEFAULT now(),
                    completed_at timestamptz,
                    CONSTRAINT notebook_media_uploads_user_idempotency_key UNIQUE (user_id, idempotency_key),
                    CONSTRAINT notebook_media_uploads_state_check CHECK (
                        state = ANY (ARRAY['uploading','ready','failed','cancelled','expired'])
                    ),
                    CONSTRAINT notebook_media_uploads_bytes_check CHECK (
                        expected_bytes >= 0 AND reserved_bytes >= 0
                    )
                );

                CREATE TABLE IF NOT EXISTS notebook_media_outbox (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    blob_id text REFERENCES notebook_media_blobs(id) ON DELETE SET NULL,
                    user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    action text NOT NULL,
                    available_at timestamptz NOT NULL DEFAULT now(),
                    attempt_count integer NOT NULL DEFAULT 0,
                    max_attempts integer NOT NULL DEFAULT 5,
                    lease_owner text,
                    leased_at timestamptz,
                    last_error_code text,
                    created_at timestamptz NOT NULL DEFAULT now(),
                    completed_at timestamptz,
                    CONSTRAINT notebook_media_outbox_action_check CHECK (
                        action = ANY (ARRAY['derive','delete','reconcile','expire_upload'])
                    )
                );

                ALTER TABLE notebook_media_blobs ALTER COLUMN state SET DEFAULT 'uploading';
                ALTER TABLE notebook_media_blobs ALTER COLUMN width SET DEFAULT 0;
                ALTER TABLE notebook_media_blobs ALTER COLUMN height SET DEFAULT 0;
                ALTER TABLE notebook_media_blobs ALTER COLUMN duration_seconds SET DEFAULT 0;
                ALTER TABLE notebook_media_blobs ALTER COLUMN derivative_bytes SET DEFAULT 0;
                ALTER TABLE notebook_media_blobs ALTER COLUMN quota_counted SET DEFAULT false;
                ALTER TABLE notebook_media_blobs ALTER COLUMN attempt_count SET DEFAULT 0;
                ALTER TABLE notebook_media_blobs ALTER COLUMN created_at SET DEFAULT now();
                ALTER TABLE notebook_media_blobs ALTER COLUMN updated_at SET DEFAULT now();
                ALTER TABLE notebook_media_uploads ALTER COLUMN reserved_bytes SET DEFAULT 0;
                ALTER TABLE notebook_media_uploads ALTER COLUMN state SET DEFAULT 'uploading';
                ALTER TABLE notebook_media_uploads ALTER COLUMN multipart_parts SET DEFAULT '[]'::jsonb;
                ALTER TABLE notebook_media_uploads ALTER COLUMN created_at SET DEFAULT now();
                ALTER TABLE notebook_media_uploads ALTER COLUMN updated_at SET DEFAULT now();
                ALTER TABLE notebook_media_outbox ALTER COLUMN available_at SET DEFAULT now();
                ALTER TABLE notebook_media_outbox ALTER COLUMN attempt_count SET DEFAULT 0;
                ALTER TABLE notebook_media_outbox ALTER COLUMN max_attempts SET DEFAULT 5;
                ALTER TABLE notebook_media_outbox ALTER COLUMN created_at SET DEFAULT now();
                ALTER TABLE notebook_media_references ALTER COLUMN created_at SET DEFAULT now();
                ALTER TABLE users ALTER COLUMN media_bytes_reserved SET DEFAULT 0;

                ALTER TABLE notebook_media_blobs
                    DROP CONSTRAINT IF EXISTS notebook_media_blobs_state_check;
                ALTER TABLE notebook_media_blobs
                    ADD CONSTRAINT notebook_media_blobs_state_check CHECK (
                        state = ANY (ARRAY['uploading','ready','gc_pending','deleting','failed'])
                    );
                ALTER TABLE notebook_media_blobs
                    DROP CONSTRAINT IF EXISTS notebook_media_blobs_bytes_check;
                ALTER TABLE notebook_media_blobs
                    ADD CONSTRAINT notebook_media_blobs_bytes_check CHECK (bytes >= 0);
                ALTER TABLE notebook_media_blobs
                    DROP CONSTRAINT IF EXISTS notebook_media_blobs_derivative_bytes_check;
                ALTER TABLE notebook_media_blobs
                    ADD CONSTRAINT notebook_media_blobs_derivative_bytes_check
                    CHECK (derivative_bytes >= 0);
                ALTER TABLE notebook_media_uploads
                    DROP CONSTRAINT IF EXISTS notebook_media_uploads_state_check;
                ALTER TABLE notebook_media_uploads
                    ADD CONSTRAINT notebook_media_uploads_state_check CHECK (
                        state = ANY (ARRAY['uploading','ready','failed','cancelled','expired'])
                    );
                ALTER TABLE notebook_media_uploads
                    DROP CONSTRAINT IF EXISTS notebook_media_uploads_bytes_check;
                ALTER TABLE notebook_media_uploads
                    ADD CONSTRAINT notebook_media_uploads_bytes_check CHECK (
                        expected_bytes >= 0 AND reserved_bytes >= 0
                    );
                ALTER TABLE notebook_media_outbox
                    DROP CONSTRAINT IF EXISTS notebook_media_outbox_action_check;
                ALTER TABLE notebook_media_outbox
                    ADD CONSTRAINT notebook_media_outbox_action_check CHECK (
                        action = ANY (ARRAY['derive','delete','reconcile','expire_upload'])
                    );

                ALTER TABLE notebook_media_references
                    DROP CONSTRAINT IF EXISTS notebook_media_references_note_blob_key;
                ALTER TABLE notebook_media_uploads
                    DROP CONSTRAINT IF EXISTS notebook_media_uploads_user_idempotency_key;

                CREATE UNIQUE INDEX IF NOT EXISTS idx_notebook_media_blobs_user_hash
                    ON notebook_media_blobs(user_id, content_hash)
                    WHERE content_hash IS NOT NULL;
                CREATE UNIQUE INDEX IF NOT EXISTS notebook_media_references_note_blob_key
                    ON notebook_media_references(note_id, blob_id);
                CREATE UNIQUE INDEX IF NOT EXISTS notebook_media_uploads_user_idempotency_key
                    ON notebook_media_uploads(user_id, idempotency_key);
                CREATE INDEX IF NOT EXISTS idx_notebook_media_blobs_state_due
                    ON notebook_media_blobs(state, delete_after, upload_expires_at);
                CREATE INDEX IF NOT EXISTS idx_notebook_media_refs_user_hash_lookup
                    ON notebook_media_references(user_id, blob_id);
                CREATE INDEX IF NOT EXISTS idx_notebook_media_refs_note
                    ON notebook_media_references(note_id);
                CREATE INDEX IF NOT EXISTS idx_notebook_media_uploads_expiry
                    ON notebook_media_uploads(state, expires_at);
                CREATE INDEX IF NOT EXISTS idx_notebook_media_outbox_claim
                    ON notebook_media_outbox(available_at, id)
                    WHERE completed_at IS NULL;

                ALTER TABLE users DROP CONSTRAINT IF EXISTS users_media_bytes_nonnegative;
                ALTER TABLE users ADD CONSTRAINT users_media_bytes_nonnegative
                    CHECK (media_bytes_used >= 0 AND media_bytes_reserved >= 0);

                INSERT INTO plan_limits (
                    plan,ai_actions_per_month,brokerage_connections,data_bytes,media_bytes,
                    workspace_limit,brokerage_history_days,advanced_analytics,
                    universal_definitions,mcp_access,desktop_access
                ) VALUES
                    ('free',15,1,NULL,(50 * 1024 * 1024)::bigint,6,365,false,false,false,false),
                    ('pro',300,5,NULL,(1024 * 1024 * 1024)::bigint,NULL,NULL,true,true,true,true)
                ON CONFLICT (plan) DO NOTHING;

                INSERT INTO notebook_media_blobs (
                    id,user_id,content_hash,object_key,state,content_type,media_type,format,
                    bytes,width,height,duration_seconds,checksum_sha256,quota_counted,created_at,updated_at
                )
                SELECT gen_random_uuid()::text, picked.user_id, picked.content_hash,
                       picked.cloudinary_public_id, 'ready', picked.content_type,
                       picked.media_type, picked.format, picked.bytes, picked.width,
                       picked.height, picked.duration_seconds, picked.content_hash, true,
                       picked.created_at, picked.created_at
                FROM (
                    SELECT DISTINCT ON (user_id, content_hash)
                           user_id,content_hash,cloudinary_public_id,content_type,
                           media_type,format,bytes,width,height,duration_seconds,created_at,id
                    FROM notebook_images
                    WHERE content_hash <> ''
                    ORDER BY user_id,content_hash,created_at,id
                ) picked
                ON CONFLICT DO NOTHING;

                INSERT INTO notebook_media_blobs (
                    id,user_id,content_hash,object_key,state,content_type,media_type,format,
                    bytes,width,height,duration_seconds,checksum_sha256,quota_counted,created_at,updated_at
                )
                SELECT gen_random_uuid()::text, image.user_id, NULL,
                       image.cloudinary_public_id, 'ready', image.content_type,
                       image.media_type, image.format, image.bytes, image.width,
                       image.height, image.duration_seconds, '', true, image.created_at, image.created_at
                FROM (
                    SELECT DISTINCT ON (user_id, cloudinary_public_id) *
                    FROM notebook_images
                    WHERE content_hash = ''
                    ORDER BY user_id,cloudinary_public_id,created_at,id
                ) image;

                INSERT INTO notebook_media_references (
                    id,blob_id,user_id,workspace_id,note_id,original_filename,created_at
                )
                SELECT image.id, blob.id, image.user_id, image.workspace_id,
                       image.note_id, image.original_filename, image.created_at
                FROM notebook_images image
                JOIN notebook_media_blobs blob
                  ON blob.user_id = image.user_id
                 AND (
                    (image.content_hash <> '' AND blob.content_hash = image.content_hash)
                    OR
                    (image.content_hash = '' AND blob.content_hash IS NULL
                     AND blob.object_key = image.cloudinary_public_id)
                 )
                ON CONFLICT DO NOTHING;

                UPDATE users user_row
                SET media_bytes_used = COALESCE((
                        SELECT sum(blob.bytes)
                        FROM notebook_media_blobs blob
                        WHERE blob.user_id = user_row.id AND blob.state = 'ready'
                    ), 0),
                    media_bytes_reserved = 0,
                    usage_recomputed_at = now();
                "#,
            )
            .await?;
        Ok(())
    }

    async fn down(&self, _manager: &SchemaManager) -> Result<(), DbErr> {
        Ok(())
    }
}
