import type {EditorThemeClasses} from 'lexical';


const theme: EditorThemeClasses = {
  autocomplete: 'text-gray-400',
  blockCursor: 'block pointer-events-none absolute after:content-[""] after:block after:absolute after:-top-0.5 after:w-5 after:border-t after:border-black after:animate-pulse',
  characterLimit: 'inline !bg-red-300',
  code: 'bg-gray-100 font-mono block py-2 px-2 pl-14 leading-relaxed text-xs my-0 mt-2 mb-2 overflow-x-auto relative [tab-size:2] before:content-[attr(data-gutter)] before:absolute before:bg-gray-200 before:left-0 before:top-0 before:border-r before:border-gray-300 before:py-2 before:px-2 before:text-gray-500 before:whitespace-pre-wrap before:text-right before:min-w-[25px]',
  codeHighlight: {
    atrule: 'text-blue-600',
    attr: 'text-blue-600',
    boolean: 'text-purple-600',
    builtin: 'text-green-600',
    cdata: 'text-gray-500 italic',
    char: 'text-green-600',
    class: 'text-orange-600',
    'class-name': 'text-orange-600',
    comment: 'text-gray-500 italic',
    constant: 'text-purple-600',
    deleted: 'bg-red-100 text-red-800',
    doctype: 'text-gray-500 italic',
    entity: 'text-red-600',
    function: 'text-orange-600',
    important: 'text-pink-600 font-bold',
    inserted: 'bg-green-100 text-green-800',
    keyword: 'text-blue-600',
    namespace: 'text-pink-600',
    number: 'text-purple-600',
    operator: 'text-red-600',
    prolog: 'text-gray-500 italic',
    property: 'text-purple-600',
    punctuation: 'text-gray-600',
    regex: 'text-pink-600',
    selector: 'text-green-600',
    string: 'text-green-600',
    symbol: 'text-purple-600',
    tag: 'text-purple-600',
    unchanged: 'text-gray-600',
    url: 'text-red-600',
    variable: 'text-pink-600',
  },
  embedBlock: {
    base: 'select-none',
    focus: 'outline outline-2 outline-blue-500',
  },
  hashtag: 'bg-blue-100 border-b border-blue-300',
  heading: {
    h1: 'text-2xl text-gray-900 font-normal m-0',
    h2: 'text-base text-gray-600 font-bold m-0 uppercase',
    h3: 'text-xs m-0 uppercase',
    h4: 'text-xs m-0 text-gray-700',
    h5: 'text-xs m-0 text-gray-700',
    h6: 'text-xs m-0 text-gray-700',
  },
  hr: 'py-0.5 px-0.5 border-0 my-4 cursor-pointer after:content-[""] after:block after:h-0.5 after:bg-gray-300 after:leading-[2px]',
  hrSelected: 'outline outline-2 outline-blue-500 select-none',
  image: 'editor-image',
  indent: '[--lexical-indent-base-value:40px]',
  inlineImage: 'inline-editor-image',
  layoutContainer: 'grid gap-2.5 my-2.5',
  layoutItem: 'border border-dashed border-gray-300 py-2 px-4 min-w-0 max-w-full',
  link: 'text-blue-600 no-underline hover:underline hover:cursor-pointer',
  list: {
    checklist: 'p-0 m-0 list-none',
    listitem: 'mx-8',
    listitemChecked: 'relative ml-2 mr-2 pl-6 pr-6 list-none outline-none block min-h-6 line-through',
    listitemUnchecked: 'relative ml-2 mr-2 pl-6 pr-6 list-none outline-none block min-h-6',
    nested: {
      listitem: 'list-none',
    },
    olDepth: [
      'p-0 m-0 list-outside',
      'p-0 m-0 list-[upper-alpha] list-outside',
      'p-0 m-0 list-[lower-alpha] list-outside',
      'p-0 m-0 list-[upper-roman] list-outside',
      'p-0 m-0 list-[lower-roman] list-outside',
    ],
    ul: 'p-0 m-0 list-outside',
  },
  ltr: 'text-left',
  mark: 'bg-yellow-100 border-b-2 border-yellow-300 pb-0.5',
  markOverlap: 'bg-yellow-200 border-b-2 border-yellow-500',
  paragraph: 'm-0 relative',
  quote: 'm-0 ml-5 mb-2.5 text-base text-gray-600 border-l-4 border-gray-300 pl-4',
  rtl: 'text-right',
  specialText: 'bg-yellow-300 font-bold',
  tab: 'relative no-underline',
  table: 'border-collapse border-spacing-0 overflow-y-scroll overflow-x-scroll table-fixed w-fit mt-6 mb-8',
  tableAddColumns: 'absolute bg-gray-200 h-full animate-[table-controls_0.2s_ease] border-0 cursor-pointer hover:bg-blue-200',
  tableAddRows: 'absolute w-[calc(100%-25px)] bg-gray-200 animate-[table-controls_0.2s_ease] border-0 cursor-pointer hover:bg-blue-200',
  tableAlignment: {
    center: 'mx-auto',
    right: 'ml-auto',
  },
  tableCell: 'border border-gray-400 w-[75px] align-top text-left py-1.5 px-2 relative outline-none overflow-auto',
  tableCellActionButton: 'bg-gray-200 block border-0 rounded-[20px] w-5 h-5 text-gray-800 cursor-pointer hover:bg-gray-300',
  tableCellActionButtonContainer: 'block right-1.5 top-1.5 absolute z-[4] w-5 h-5',
  tableCellHeader: 'bg-gray-100 text-left',
  tableCellResizer: 'absolute -right-1 h-full w-2 cursor-ew-resize z-10 top-0',
  tableCellSelected: 'caret-color-transparent after:absolute after:left-0 after:right-0 after:bottom-0 after:top-0 after:bg-highlight after:mix-blend-multiply after:content-[""] after:pointer-events-none',
  tableFrozenColumn: '[&_tr>td:first-child]:bg-white [&_tr>td:first-child]:sticky [&_tr>td:first-child]:z-[2] [&_tr>td:first-child]:left-0 [&_tr>th:first-child]:bg-gray-100 [&_tr>th:first-child]:sticky [&_tr>th:first-child]:z-[2] [&_tr>th:first-child]:left-0',
  tableFrozenRow: 'overflow-x-clip [&_tr:first-child>td]:overflow-clip [&_tr:first-child>td]:bg-white [&_tr:first-child>td]:sticky [&_tr:first-child>td]:z-[2] [&_tr:first-child>td]:top-11 [&_tr:first-child>th]:overflow-clip [&_tr:first-child>th]:bg-gray-100 [&_tr:first-child>th]:sticky [&_tr:first-child>th]:z-[2] [&_tr:first-child>th]:top-11',
  tableRowStriping: '[&_tr:nth-child(even)]:bg-blue-50',
  tableScrollableWrapper: 'overflow-x-auto mx-0 mr-6 mb-8',
  tableSelected: 'outline outline-2 outline-blue-500',
  tableSelection: '[&_*::selection]:bg-transparent',
  text: {
    bold: 'font-bold',
    capitalize: 'capitalize',
    code: 'bg-gray-100 py-0.5 px-1 font-mono text-[94%]',
    highlight: 'bg-yellow-100 border-b-2 border-yellow-300',
    italic: 'italic',
    lowercase: 'lowercase',
    strikethrough: 'line-through',
    subscript: 'text-xs align-sub',
    superscript: 'text-xs align-super',
    underline: 'underline',
    underlineStrikethrough: 'underline line-through',
    uppercase: 'uppercase',
  },
};

export default theme;
