-- Income Statement Table - GLOBAL SHARED DATA
-- This table stores income statement data for companies, accessible to ALL users.
-- Data is sourced from market data providers and is shared across the platform.
-- This table uses a "wide" format, where each financial metric is a separate column.

CREATE TABLE IF NOT EXISTS income_statement (
    id BIGSERIAL PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    frequency VARCHAR(10) NOT NULL, -- 'annual' or 'quarterly'
    fiscal_date DATE NOT NULL,

    -- Revenue & Profit
    total_revenue NUMERIC(25, 2),
    operating_revenue NUMERIC(25, 2),
    cost_of_revenue NUMERIC(25, 2),
    gross_profit NUMERIC(25, 2),
    reconciled_cost_of_revenue NUMERIC(25, 2),

    -- Expenses
    operating_expense NUMERIC(25, 2),
    selling_general_and_administrative NUMERIC(25, 2),
    research_and_development NUMERIC(25, 2),
    total_expenses NUMERIC(25, 2),
    reconciled_depreciation NUMERIC(25, 2),

    -- Income
    operating_income NUMERIC(25, 2),
    total_operating_income_as_reported NUMERIC(25, 2),
    net_non_operating_interest_income_expense NUMERIC(25, 2),
    non_operating_interest_income NUMERIC(25, 2),
    non_operating_interest_expense NUMERIC(25, 2),
    other_income_expense NUMERIC(25, 2),
    other_non_operating_income_expenses NUMERIC(25, 2),
    pretax_income NUMERIC(25, 2),
    net_income_common_stockholders NUMERIC(25, 2),
    net_income_attributable_to_parent_shareholders NUMERIC(25, 2),
    net_income_including_non_controlling_interests NUMERIC(25, 2),
    net_income_continuous_operations NUMERIC(25, 2),
    diluted_ni_available_to_common_stockholders NUMERIC(25, 2),
    net_income_from_continuing_discontinued_operation NUMERIC(25, 2),
    net_income_from_continuing_operation_net_minority_interest NUMERIC(25, 2),
    normalized_income NUMERIC(25, 2),

    -- Interest
    interest_income NUMERIC(25, 2),
    interest_expense NUMERIC(25, 2),
    net_interest_income NUMERIC(25, 2),

    -- EPS & Shares
    basic_eps NUMERIC(10, 4),
    diluted_eps NUMERIC(10, 4),
    basic_average_shares BIGINT,
    diluted_average_shares BIGINT,

    -- Other Metrics
    ebit NUMERIC(25, 2),
    ebitda NUMERIC(25, 2),
    normalized_ebitda NUMERIC(25, 2),
    tax_provision NUMERIC(25, 2),
    tax_rate_for_calcs NUMERIC(10, 4),
    tax_effect_of_unusual_items NUMERIC(25, 2),

    -- Metadata
    data_provider VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    -- Ensure one record per period per provider
    UNIQUE(symbol, frequency, fiscal_date, data_provider)
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_income_statement_symbol_freq_date ON income_statement (symbol, frequency, fiscal_date);
CREATE INDEX IF NOT EXISTS idx_income_statement_provider ON income_statement (data_provider);

-- Add table and column comments
COMMENT ON TABLE income_statement IS '''Stores detailed income statement financial data (both annual and quarterly) for companies from various data providers. This table uses a "wide" format where each financial metric is a separate column.''';

COMMENT ON COLUMN income_statement.id IS '''Unique identifier for each record.''';
COMMENT ON COLUMN income_statement.symbol IS '''Stock ticker symbol, references company_info(symbol).''';
COMMENT ON COLUMN income_statement.frequency IS '''Frequency of the report: ''annual'' or ''quarterly''.''';
COMMENT ON COLUMN income_statement.fiscal_date IS '''The end date of the fiscal period for the report.''';

-- Revenue & Profit Comments
COMMENT ON COLUMN income_statement.total_revenue IS '''Total revenue generated by the company.''';
COMMENT ON COLUMN income_statement.operating_revenue IS '''Revenue generated from primary business operations.''';
COMMENT ON COLUMN income_statement.cost_of_revenue IS '''The cost of goods sold and other direct costs associated with revenue generation.''';
COMMENT ON COLUMN income_statement.gross_profit IS '''Total Revenue - Cost of Revenue.''';
COMMENT ON COLUMN income_statement.reconciled_cost_of_revenue IS '''Cost of revenue reconciled with other financial statements.''';

-- Expenses Comments
COMMENT ON COLUMN income_statement.operating_expense IS '''Total expenses incurred through normal business operations.''';
COMMENT ON COLUMN income_statement.selling_general_and_administrative IS '''Selling, general, and administrative expenses (SG&A).''';
COMMENT ON COLUMN income_statement.research_and_development IS '''Research and Development (R&D) expenses.''';
COMMENT ON COLUMN income_statement.total_expenses IS '''Sum of all operating and non-operating expenses.''';
COMMENT ON COLUMN income_statement.reconciled_depreciation IS '''Depreciation expenses reconciled with other financial statements.''';

-- Income Comments
COMMENT ON COLUMN income_statement.operating_income IS '''Gross Profit - Operating Expenses.''';
COMMENT ON COLUMN income_statement.total_operating_income_as_reported IS '''Operating income as reported in financial statements.''';
COMMENT ON COLUMN income_statement.net_non_operating_interest_income_expense IS '''Net income or expense from non-operating interest.''';
COMMENT ON COLUMN income_statement.non_operating_interest_income IS '''Income from investments and other non-primary business activities.''';
COMMENT ON COLUMN income_statement.non_operating_interest_expense IS '''Expenses from non-operating activities, like interest on debt.''';
COMMENT ON COLUMN income_statement.other_income_expense IS '''Other miscellaneous income or expenses.''';
COMMENT ON COLUMN income_statement.other_non_operating_income_expenses IS '''Other non-operating income and expenses.''';
COMMENT ON COLUMN income_statement.pretax_income IS '''Income before taxes.''';
COMMENT ON COLUMN income_statement.net_income_common_stockholders IS '''Net income available to common stockholders.''';
COMMENT ON COLUMN income_statement.net_income_attributable_to_parent_shareholders IS '''Net income attributable to the parent company''s shareholders.''';
COMMENT ON COLUMN income_statement.net_income_including_non_controlling_interests IS '''Net income including the portion attributable to non-controlling interests.''';
COMMENT ON COLUMN income_statement.net_income_continuous_operations IS '''Net income from continuing business operations.''';
COMMENT ON COLUMN income_statement.diluted_ni_available_to_common_stockholders IS '''Diluted net income available to common stockholders.''';
COMMENT ON COLUMN income_statement.net_income_from_continuing_discontinued_operation IS '''Net income from both continuing and discontinued operations.''';
COMMENT ON COLUMN income_statement.net_income_from_continuing_operation_net_minority_interest IS '''Net income from continuing operations net of minority interest.''';
COMMENT ON COLUMN income_statement.normalized_income IS '''Net income adjusted for non-recurring items.''';

-- Interest Comments
COMMENT ON COLUMN income_statement.interest_income IS '''Income earned from interest-bearing assets.''';
COMMENT ON COLUMN income_statement.interest_expense IS '''Cost of borrowed funds.''';
COMMENT ON COLUMN income_statement.net_interest_income IS '''Interest Income - Interest Expense.''';

-- EPS & Shares Comments
COMMENT ON COLUMN income_statement.basic_eps IS '''Basic Earnings Per Share.''';
COMMENT ON COLUMN income_statement.diluted_eps IS '''Diluted Earnings Per Share.''';
COMMENT ON COLUMN income_statement.basic_average_shares IS '''Average number of basic shares outstanding.''';
COMMENT ON COLUMN income_statement.diluted_average_shares IS '''Average number of diluted shares outstanding.''';

-- Other Metrics Comments
COMMENT ON COLUMN income_statement.ebit IS '''Earnings Before Interest and Taxes.''';
COMMENT ON COLUMN income_statement.ebitda IS '''Earnings Before Interest, Taxes, Depreciation, and Amortization.''';
COMMENT ON COLUMN income_statement.normalized_ebitda IS '''EBITDA adjusted for non-recurring items.''';
COMMENT ON COLUMN income_statement.tax_provision IS '''Provision for income taxes.''';
COMMENT ON COLUMN income_statement.tax_rate_for_calcs IS '''Effective tax rate used for calculations.''';
COMMENT ON COLUMN income_statement.tax_effect_of_unusual_items IS '''Tax impact of unusual or non-recurring items.''';

-- Metadata Comments
COMMENT ON COLUMN income_statement.data_provider IS '''The source of the market data (e.g., ''fmp'', ''alpha_vantage'').''';
COMMENT ON COLUMN income_statement.created_at IS '''Timestamp of when the record was first created.''';
COMMENT ON COLUMN income_statement.updated_at IS '''Timestamp of when the record was last updated.''';

-- =====================================================
-- INCOME STATEMENT TABLE SECURITY POLICY
-- READ-ONLY POLICY: Users can only view data, no modifications allowed.
-- =====================================================

-- Enable Row Level Security on the table
ALTER TABLE income_statement ENABLE ROW LEVEL SECURITY;

-- Grant SELECT permission to all authenticated users
GRANT SELECT ON income_statement TO PUBLIC;

-- Revoke modification permissions
REVOKE INSERT, UPDATE, DELETE ON income_statement FROM PUBLIC;

-- Create policies to enforce read-only access for users
CREATE POLICY "income_statement_select_policy" ON income_statement
    FOR SELECT
    USING (true); -- Allow all users to read all rows

CREATE POLICY "income_statement_insert_policy" ON income_statement
    FOR INSERT
    WITH CHECK (false); -- Deny all insert operations

CREATE POLICY "income_statement_update_policy" ON income_statement
    FOR UPDATE
    USING (false)
    WITH CHECK (false); -- Deny all update operations

CREATE POLICY "income_statement_delete_policy" ON income_statement
    FOR DELETE
    USING (false); -- Deny all delete operations