//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "agent_index_outbox")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text", unique_key = "idx_agent_index_outbox_one_queued")]
    pub user_id: String,
    #[sea_orm(column_type = "Text", unique_key = "idx_agent_index_outbox_one_queued")]
    pub workspace_id: String,
    #[sea_orm(column_type = "Text", unique_key = "idx_agent_index_outbox_one_queued")]
    pub source_type: String,
    #[sea_orm(column_type = "Text", unique_key = "idx_agent_index_outbox_one_queued")]
    pub source_id: String,
    #[sea_orm(column_type = "Text")]
    pub operation: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub available_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub lease_owner: Option<String>,
    pub leased_at: Option<DateTimeWithTimeZone>,
    pub heartbeat_at: Option<DateTimeWithTimeZone>,
    pub attempt_count: i32,
    pub max_attempts: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_code: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub completed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces: BelongsTo<crate::entities::core::workspaces::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
