//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "agent_claim_evidence")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        column_type = "Text",
        unique_key = "agent_claim_evidence_claim_id_ordinal_key"
    )]
    pub claim_id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub evidence_id: String,
    #[sea_orm(unique_key = "agent_claim_evidence_claim_id_ordinal_key")]
    pub ordinal: i32,
    #[sea_orm(
        belongs_to,
        from = "claim_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub agent_claims: BelongsTo<crate::entities::agents::agent_claims::Entity>,
    #[sea_orm(
        belongs_to,
        from = "evidence_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub agent_evidence: BelongsTo<crate::entities::agents::agent_evidence::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
