//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "agent_memories")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "idx_agent_memories_one_active_subject"
    )]
    pub user_id: String,
    #[sea_orm(
        column_type = "Text",
        nullable,
        unique_key = "idx_agent_memories_one_active_subject"
    )]
    pub workspace_id: Option<String>,
    #[sea_orm(
        column_type = "Text",
        unique_key = "idx_agent_memories_one_active_subject"
    )]
    pub kind: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "idx_agent_memories_one_active_subject"
    )]
    pub subject_key: String,
    #[sea_orm(column_type = "Text")]
    pub text: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub pinned: bool,
    #[sea_orm(column_type = "Text")]
    pub source_conversation_id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "agent_memories_source_message_id_normalized_hash_key"
    )]
    pub source_message_id: String,
    #[sea_orm(column_type = "Text")]
    pub provenance_excerpt: String,
    #[sea_orm(column_type = "Double")]
    pub confidence: f64,
    #[sea_orm(column_type = "Text")]
    pub extraction_version: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "agent_memories_source_message_id_normalized_hash_key"
    )]
    pub normalized_hash: String,
    pub user_edited: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub superseded_by: Option<String>,
    pub use_count: i64,
    pub last_used_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        belongs_to,
        from = "source_conversation_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub agent_conversations: BelongsTo<crate::entities::agents::agent_conversations::Entity>,
    #[sea_orm(
        belongs_to,
        from = "source_message_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub agent_messages: BelongsTo<crate::entities::agents::agent_messages::Entity>,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "superseded_by",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub agent_memories: BelongsTo<Option<Entity>>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces: BelongsTo<Option<crate::entities::core::workspaces::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
