//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "agent_evidence")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "agent_evidence_run_id_idempotency_key_key"
    )]
    pub run_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub tool_call_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub workspace_id: String,
    #[sea_orm(column_type = "Text")]
    pub source_type: String,
    #[sea_orm(column_type = "Text")]
    pub source_id: String,
    #[sea_orm(column_type = "Text")]
    pub source_version: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub excerpt: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub source_url: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub freshness: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub payload_json: Json,
    #[sea_orm(
        column_type = "Text",
        nullable,
        unique_key = "agent_evidence_run_id_idempotency_key_key"
    )]
    pub idempotency_key: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "run_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub agent_runs: BelongsTo<crate::entities::agents::agent_runs::Entity>,
    #[sea_orm(
        belongs_to,
        from = "tool_call_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub agent_tool_calls: BelongsTo<Option<crate::entities::agents::agent_tool_calls::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces: BelongsTo<crate::entities::core::workspaces::Entity>,
    #[sea_orm(has_many, via = "agent_claim_evidence")]
    pub agent_claims: HasMany<crate::entities::agents::agent_claims::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
