//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "agent_assistance_requests")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "agent_assistance_requests_user_id_idempotency_key_key"
    )]
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub workload: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "agent_assistance_requests_user_id_idempotency_key_key"
    )]
    pub idempotency_key: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub input_tokens: i64,
    pub output_tokens: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_code: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub completed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
