//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "agent_knowledge_passages")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "agent_knowledge_passages_user_id_workspace_id_source_type_s_key"
    )]
    pub user_id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "agent_knowledge_passages_user_id_workspace_id_source_type_s_key"
    )]
    pub workspace_id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "agent_knowledge_passages_user_id_workspace_id_source_type_s_key"
    )]
    pub source_type: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "agent_knowledge_passages_user_id_workspace_id_source_type_s_key"
    )]
    pub source_id: String,
    #[sea_orm(column_type = "Text")]
    pub source_version: String,
    #[sea_orm(unique_key = "agent_knowledge_passages_user_id_workspace_id_source_type_s_key")]
    pub chunk_index: i32,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub excerpt: String,
    #[sea_orm(column_type = "Text")]
    pub search_text: String,
    #[sea_orm(column_type = r#"custom("text[]")"#)]
    pub trade_ids: Vec<String>,
    #[sea_orm(column_type = r#"custom("text[]")"#)]
    pub playbook_ids: Vec<String>,
    #[sea_orm(column_type = r#"custom("text[]")"#)]
    pub note_ids: Vec<String>,
    #[sea_orm(column_type = r#"custom("text[]")"#)]
    pub symbols: Vec<String>,
    pub effective_from: Option<DateTimeWithTimeZone>,
    pub effective_to: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub content_hash: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces: BelongsTo<crate::entities::core::workspaces::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
