//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "agent_conversations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub workspace_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub title: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub summary_text: Option<String>,
    pub summarized_through_sequence: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub summary_version: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub agent_action_proposals: HasMany<crate::entities::agents::agent_action_proposals::Entity>,
    #[sea_orm(has_one)]
    pub agent_conversation_summary_jobs:
        HasOne<crate::entities::agents::agent_conversation_summary_jobs::Entity>,
    #[sea_orm(has_many)]
    pub agent_memory_jobs: HasMany<crate::entities::agents::agent_memory_jobs::Entity>,
    #[sea_orm(has_many)]
    pub agent_messages: HasMany<crate::entities::agents::agent_messages::Entity>,
    #[sea_orm(has_many)]
    pub agent_runs: HasMany<crate::entities::agents::agent_runs::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces: BelongsTo<crate::entities::core::workspaces::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
