//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "agent_action_proposals")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "agent_action_proposals_run_id_tool_call_id_key"
    )]
    pub run_id: String,
    #[sea_orm(
        column_type = "Text",
        nullable,
        unique_key = "agent_action_proposals_run_id_tool_call_id_key"
    )]
    pub tool_call_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub conversation_id: String,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub workspace_id: String,
    #[sea_orm(column_type = "Text")]
    pub kind: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub payload_json: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub preview_json: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub expected_versions_json: Json,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub expires_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub approved_by_user_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub approved_by_clerk_id: Option<String>,
    pub approved_at: Option<DateTimeWithTimeZone>,
    pub rejected_at: Option<DateTimeWithTimeZone>,
    pub executed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_code: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(has_one)]
    pub agent_action_executions: HasOne<crate::entities::agents::agent_action_executions::Entity>,
    #[sea_orm(
        belongs_to,
        from = "conversation_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub agent_conversations: BelongsTo<crate::entities::agents::agent_conversations::Entity>,
    #[sea_orm(
        belongs_to,
        from = "run_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub agent_runs: BelongsTo<crate::entities::agents::agent_runs::Entity>,
    #[sea_orm(
        belongs_to,
        from = "tool_call_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub agent_tool_calls: BelongsTo<Option<crate::entities::agents::agent_tool_calls::Entity>>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users2",
        from = "approved_by_user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub users_2: BelongsTo<Option<crate::entities::core::users::Entity>>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users1",
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users_1: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces: BelongsTo<crate::entities::core::workspaces::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
