//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "agent_messages")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "agent_messages_conversation_id_sequence_key"
    )]
    pub conversation_id: String,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub workspace_id: String,
    #[sea_orm(unique_key = "agent_messages_conversation_id_sequence_key")]
    pub sequence: i64,
    #[sea_orm(column_type = "Text")]
    pub role: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub content_json: Json,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub agent_claims: HasMany<crate::entities::agents::agent_claims::Entity>,
    #[sea_orm(
        belongs_to,
        from = "conversation_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub agent_conversations: BelongsTo<crate::entities::agents::agent_conversations::Entity>,
    #[sea_orm(has_many)]
    pub agent_memory_jobs: HasMany<crate::entities::agents::agent_memory_jobs::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces: BelongsTo<crate::entities::core::workspaces::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
