//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "agent_runs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub conversation_id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "agent_runs_user_id_idempotency_key_key"
    )]
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub workspace_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub parent_run_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub input_message_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub output_message_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "agent_runs_user_id_idempotency_key_key"
    )]
    pub idempotency_key: String,
    pub budget_reserved_at: Option<DateTimeWithTimeZone>,
    pub next_event_sequence: i64,
    pub model_calls: i64,
    pub tool_calls: i64,
    pub input_tokens: i64,
    pub output_tokens: i64,
    pub cached_input_tokens: i64,
    pub estimated_cost_micros: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub lease_owner: Option<String>,
    pub leased_at: Option<DateTimeWithTimeZone>,
    pub heartbeat_at: Option<DateTimeWithTimeZone>,
    pub attempt_count: i32,
    pub max_attempts: i32,
    pub cancel_requested_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_code: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub completed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(has_many)]
    pub agent_action_proposals: HasMany<crate::entities::agents::agent_action_proposals::Entity>,
    #[sea_orm(has_many)]
    pub agent_claims: HasMany<crate::entities::agents::agent_claims::Entity>,
    #[sea_orm(
        belongs_to,
        from = "conversation_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub agent_conversations: BelongsTo<crate::entities::agents::agent_conversations::Entity>,
    #[sea_orm(has_many)]
    pub agent_evidences: HasMany<crate::entities::agents::agent_evidence::Entity>,
    #[sea_orm(has_many)]
    pub agent_memory_jobs: HasMany<crate::entities::agents::agent_memory_jobs::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "AgentMessagesInput",
        from = "input_message_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub agent_messages_input: BelongsTo<Option<crate::entities::agents::agent_messages::Entity>>,
    #[sea_orm(
        belongs_to,
        relation_enum = "AgentMessagesOutput",
        from = "output_message_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub agent_messages_output: BelongsTo<Option<crate::entities::agents::agent_messages::Entity>>,
    #[sea_orm(has_many)]
    pub agent_run_events: HasMany<crate::entities::agents::agent_run_events::Entity>,
    #[sea_orm(has_many)]
    pub agent_run_items: HasMany<crate::entities::agents::agent_run_items::Entity>,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "parent_run_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub agent_runs: BelongsTo<Option<Entity>>,
    #[sea_orm(has_many)]
    pub agent_tool_calls: HasMany<crate::entities::agents::agent_tool_calls::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces: BelongsTo<crate::entities::core::workspaces::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
