//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "market_watchlist_symbols")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub watchlist_id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub symbol: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "watchlist_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub market_watchlists: BelongsTo<crate::entities::markets::market_watchlists::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
