//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "account_equity_history")]
pub struct Model {
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub workspace_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub date: Date,
    #[sea_orm(column_type = "Double")]
    pub cash: f64,
    #[sea_orm(column_type = "Double")]
    pub positions_value: f64,
    #[sea_orm(column_type = "Double")]
    pub equity: f64,
    #[sea_orm(column_type = "Double")]
    pub net_contributions: f64,
    #[sea_orm(column_type = "Double")]
    pub funding_adjusted_equity: f64,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces: BelongsTo<crate::entities::core::workspaces::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
