//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "journal_entries")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        column_type = "Text",
        unique_key = "idx_journal_entry_owner"
    )]
    pub id: String,
    #[sea_orm(column_type = "Text", unique_key = "idx_journal_entry_owner")]
    pub user_id: String,
    #[sea_orm(column_type = "Text", unique_key = "idx_journal_entry_owner")]
    pub workspace_id: String,
    pub open_date: Option<DateTimeWithTimeZone>,
    pub close_date: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Double", nullable)]
    pub entry_price: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub exit_price: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub position_size: Option<f64>,
    #[sea_orm(column_type = "Text")]
    pub symbol: String,
    #[sea_orm(column_type = "Text")]
    pub symbol_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub status: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub total_pl: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub net_roi: Option<f64>,
    pub duration: Option<i64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub stop_loss: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub risk_reward: Option<f64>,
    #[sea_orm(column_type = "Text")]
    pub trade_type: String,
    #[sea_orm(column_type = "Text")]
    pub mistakes: String,
    #[sea_orm(column_type = "Text")]
    pub entry_tactics: String,
    #[sea_orm(column_type = "Text")]
    pub edges_spotted: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub playbook_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub broke_30min_rule: Option<bool>,
    pub pre_trade_conviction: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub market_regime: Option<String>,
    pub is_planned_pre_market: Option<bool>,
    pub revenge_trade: Option<bool>,
    pub rule_adherence_score: Option<i32>,
    pub created_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub hlc: String,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Double")]
    pub contract_multiplier: f64,
    #[sea_orm(column_type = "Text")]
    pub source_kind: String,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub episode_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub lifecycle_state: String,
    #[sea_orm(column_type = "Text")]
    pub outcome: String,
    pub remaining_quantity: Option<Decimal>,
    pub realized_net: Option<Decimal>,
    pub fees_paid: Option<Decimal>,
    #[sea_orm(column_type = "Text", nullable)]
    pub currency: Option<String>,
    pub materialized_revision: i64,
    pub record_version: i64,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub issue_json: Option<Json>,
    pub retired_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub successor_id: Option<String>,
    #[sea_orm(
        belongs_to,
        from = "episode_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub trade_episodes: BelongsTo<Option<crate::entities::trading::trade_episodes::Entity>>,
    #[sea_orm(
        self_ref,
        relation_enum = "Successor",
        from = "successor_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub successor: BelongsTo<Option<Entity>>,
    #[sea_orm(has_one)]
    pub brokerage_episode_publications:
        HasOne<crate::entities::brokerage::brokerage_episode_publications::Entity>,
    #[sea_orm(has_many)]
    pub journal_brokerage_links: HasMany<crate::entities::trading::journal_brokerage_links::Entity>,
    #[sea_orm(
        belongs_to,
        from = "playbook_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub playbooks: BelongsTo<Option<crate::entities::trading::playbooks::Entity>>,
    #[sea_orm(has_one)]
    pub trade_review_publications:
        HasOne<crate::entities::trading::trade_review_publications::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces: BelongsTo<crate::entities::core::workspaces::Entity>,
    #[sea_orm(has_many, via = "notebook_note_trades")]
    pub notebook_notes: HasMany<crate::entities::notebook::notebook_notes::Entity>,
    #[sea_orm(has_many, via = "trade_tags")]
    pub tags: HasMany<crate::entities::trading::tags::Entity>,
    #[sea_orm(has_many, via = "trade_principle_violations")]
    pub trading_principles: HasMany<crate::entities::trading::trading_principles::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
