//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "journal_brokerage_links")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", unique_key = "idx_journal_link_entry_execution")]
    pub journal_entry_id: String,
    #[sea_orm(column_type = "Text", unique_key = "idx_journal_link_entry_execution")]
    pub brokerage_transaction_id: String,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    pub created_at: DateTimeWithTimeZone,
    pub allocated_quantity: Option<Decimal>,
    #[sea_orm(
        belongs_to,
        from = "journal_entry_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub journal_entries: BelongsTo<crate::entities::trading::journal_entries::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
