//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "manual_execution_claims")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "idx_manual_execution_claims_active_tranche"
    )]
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub workspace_id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "idx_manual_execution_claims_active_tranche"
    )]
    pub plan_id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "idx_manual_execution_claims_active_tranche"
    )]
    pub tranche_id: String,
    pub quantity: Decimal,
    pub price: Decimal,
    pub executed_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub reconciled_match_id: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "plan_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub position_calculator_plans:
        BelongsTo<crate::entities::calculator::position_calculator_plans::Entity>,
    #[sea_orm(
        belongs_to,
        from = "reconciled_match_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub trade_episode_matches:
        BelongsTo<Option<crate::entities::trading::trade_episode_matches::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces: BelongsTo<crate::entities::core::workspaces::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
