//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "playbooks")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        column_type = "Text",
        unique_key = "idx_playbooks_id_workspace"
    )]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub edge_name: String,
    #[sea_orm(column_type = "Text")]
    pub entry_rules: String,
    #[sea_orm(column_type = "Text")]
    pub exit_rules: String,
    #[sea_orm(column_type = "Text")]
    pub position_sizing_rules: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub additional_rules: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub hlc: String,
    #[sea_orm(column_type = "Text", unique_key = "idx_playbooks_id_workspace")]
    pub workspace_id: String,
    #[sea_orm(column_type = "Text")]
    pub availability: String,
    #[sea_orm(has_many)]
    pub journal_entries: HasMany<crate::entities::trading::journal_entries::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(has_many, via = "playbook_workspace_applicability")]
    pub workspaces: HasMany<crate::entities::core::workspaces::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
