//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "tag_categories")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        column_type = "Text",
        unique_key = "idx_tag_categories_id_workspace"
    )]
    pub id: String,
    #[sea_orm(column_type = "Text", unique, unique_key = "idx_tagcat_user_role")]
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable, unique_key = "idx_tagcat_user_role")]
    pub role: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub color: Option<String>,
    pub sort_order: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub hlc: String,
    #[sea_orm(column_type = "Text", unique_key = "idx_tag_categories_id_workspace")]
    pub workspace_id: String,
    #[sea_orm(column_type = "Text")]
    pub availability: String,
    #[sea_orm(has_many)]
    pub tags: HasMany<crate::entities::trading::tags::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(has_many, via = "tag_category_workspace_applicability")]
    pub workspaces: HasMany<crate::entities::core::workspaces::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
