//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "tags")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", unique_key = "idx_tags_user_cat_name")]
    pub user_id: String,
    #[sea_orm(column_type = "Text", unique_key = "idx_tags_user_cat_name")]
    pub category_id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub color: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub hlc: String,
    #[sea_orm(column_type = "Text")]
    pub workspace_id: String,
    #[sea_orm(
        belongs_to,
        from = "category_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub tag_categories: BelongsTo<crate::entities::trading::tag_categories::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Workspaces2",
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces_2: BelongsTo<crate::entities::core::workspaces::Entity>,
    #[sea_orm(has_many, via = "trade_tags")]
    pub journal_entries: HasMany<crate::entities::trading::journal_entries::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
