//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "trading_principles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub workspace_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub playbook_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub evidence_note_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub the_rule: String,
    #[sea_orm(column_type = "Text")]
    pub why: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub intervention: Option<String>,
    pub priority: i64,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub hlc: String,
    #[sea_orm(
        belongs_to,
        from = "evidence_note_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub notebook_notes: BelongsTo<Option<crate::entities::notebook::notebook_notes::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "playbook_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub playbooks: BelongsTo<Option<crate::entities::trading::playbooks::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces: BelongsTo<crate::entities::core::workspaces::Entity>,
    #[sea_orm(has_many, via = "trade_principle_violations")]
    pub journal_entries: HasMany<crate::entities::trading::journal_entries::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
