//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "trade_review_versions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub workspace_id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "trade_review_versions_match_id_version_number_key"
    )]
    pub match_id: String,
    #[sea_orm(unique_key = "trade_review_versions_match_id_version_number_key")]
    pub version_number: i32,
    #[sea_orm(column_type = "Text")]
    pub stage: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub plan_snapshot_json: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub calculation_json: Json,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub reflection_json: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub journal_draft_json: Option<Json>,
    pub finalized_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub supersedes_id: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "match_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub trade_episode_matches: BelongsTo<crate::entities::trading::trade_episode_matches::Entity>,
    #[sea_orm(has_one)]
    pub trade_review_publications:
        HasOne<crate::entities::trading::trade_review_publications::Entity>,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "supersedes_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub trade_review_versions: BelongsTo<Option<Entity>>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces: BelongsTo<crate::entities::core::workspaces::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
