//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "trade_tags")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub journal_entry_id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub tag_id: String,
    #[sea_orm(
        belongs_to,
        from = "journal_entry_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub journal_entries: BelongsTo<crate::entities::trading::journal_entries::Entity>,
    #[sea_orm(
        belongs_to,
        from = "tag_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub tags: BelongsTo<crate::entities::trading::tags::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
