//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "trade_review_publications")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub review_version_id: String,
    #[sea_orm(column_type = "Text", unique)]
    pub journal_entry_id: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "journal_entry_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub journal_entries: BelongsTo<crate::entities::trading::journal_entries::Entity>,
    #[sea_orm(
        belongs_to,
        from = "review_version_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub trade_review_versions: BelongsTo<crate::entities::trading::trade_review_versions::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
