//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "trade_episodes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "trade_episodes_user_id_workspace_id_fingerprint_key"
    )]
    pub user_id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "trade_episodes_user_id_workspace_id_fingerprint_key"
    )]
    pub workspace_id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "trade_episodes_user_id_workspace_id_fingerprint_key"
    )]
    pub fingerprint: String,
    #[sea_orm(column_type = "Text")]
    pub instrument_key: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub instrument_json: Json,
    #[sea_orm(column_type = "Text")]
    pub direction: String,
    pub opened_at: DateTimeWithTimeZone,
    pub closed_at: Option<DateTimeWithTimeZone>,
    pub current_quantity: Decimal,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub block_reason: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub grouping_source: String,
    #[sea_orm(has_one)]
    pub brokerage_episode_publications:
        HasOne<crate::entities::brokerage::brokerage_episode_publications::Entity>,
    #[sea_orm(has_many)]
    pub trade_episode_fills: HasMany<crate::entities::trading::trade_episode_fills::Entity>,
    #[sea_orm(has_one)]
    pub trade_episode_matches: HasOne<crate::entities::trading::trade_episode_matches::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces: BelongsTo<crate::entities::core::workspaces::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
