//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "trade_episode_matches")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub workspace_id: String,
    #[sea_orm(column_type = "Text", unique)]
    pub episode_id: String,
    #[sea_orm(column_type = "Text")]
    pub plan_id: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub score: Decimal,
    #[sea_orm(column_type = "JsonBinary")]
    pub evidence_json: Json,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub manual_execution_claims: HasMany<crate::entities::trading::manual_execution_claims::Entity>,
    #[sea_orm(
        belongs_to,
        from = "plan_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub position_calculator_plans:
        BelongsTo<crate::entities::calculator::position_calculator_plans::Entity>,
    #[sea_orm(
        belongs_to,
        from = "episode_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub trade_episodes: BelongsTo<crate::entities::trading::trade_episodes::Entity>,
    #[sea_orm(has_many)]
    pub trade_review_versions: HasMany<crate::entities::trading::trade_review_versions::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces: BelongsTo<crate::entities::core::workspaces::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
