//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "trade_episode_fills")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "trade_episode_fills_episode_id_brokerage_transaction_id_rol_key"
    )]
    pub episode_id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "trade_episode_fills_episode_id_brokerage_transaction_id_rol_key"
    )]
    pub brokerage_transaction_id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "trade_episode_fills_episode_id_brokerage_transaction_id_rol_key"
    )]
    pub role: String,
    pub quantity: Decimal,
    pub price: Decimal,
    pub fee: Decimal,
    pub executed_at: DateTimeWithTimeZone,
    pub allocation_order: i32,
    #[sea_orm(
        belongs_to,
        from = "brokerage_transaction_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub brokerage_transactions:
        BelongsTo<crate::entities::brokerage::brokerage_transactions::Entity>,
    #[sea_orm(
        belongs_to,
        from = "episode_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub trade_episodes: BelongsTo<crate::entities::trading::trade_episodes::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
