pub(crate) mod block_chunking;
pub mod chunking;
mod conversation_summary;
mod embedding;
mod indexing;
mod memory_extraction;
pub mod memory_policy;
mod memory_recall;
mod rerank;
mod retrieval;
mod service;
pub mod sources;
mod store;
mod types;
mod voyage;
mod worker;

pub use conversation_summary::run_conversation_summary_worker;
pub use embedding::{EmbeddingProvider, VoyageEmbeddingProvider};
pub use indexing::KnowledgeIndexer;
pub use memory_extraction::run_memory_worker;
pub use memory_recall::{build_memory_context, recall as recall_memories};
pub use rerank::{Reranker, VoyageReranker};
pub use retrieval::{KnowledgeCandidate, gather_candidates};
pub use service::KnowledgeService;
pub use store::KnowledgeStore;
pub use types::*;
pub use voyage::{VoyageClient, VoyageConfig};
pub use worker::run_knowledge_worker;
