export const FEATURE_FLAGS = {
  USE_REPLICACHE_JOURNAL: process.env.NEXT_PUBLIC_USE_REPLICACHE_JOURNAL === 'true',
  USE_REPLICACHE_NOTES: process.env.NEXT_PUBLIC_USE_REPLICACHE_NOTES === 'true',
  USE_REPLICACHE_PLAYBOOK: process.env.NEXT_PUBLIC_USE_REPLICACHE_PLAYBOOK === 'true',
};
