//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "journal_trade_context")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub entry_id: String,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub workspace_id: String,
    pub record_version: i64,
    #[sea_orm(column_type = "Text")]
    pub stop_state: String,
    pub stop_price: Option<Decimal>,
    #[sea_orm(column_type = "Text", nullable)]
    pub playbook_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub companion_note_id: Option<String>,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        relation_enum = "JournalEntries2",
        from = "entry_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub journal_entries_2: BelongsTo<crate::entities::trading::journal_entries::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "JournalEntries1",
        from = "(entry_id, user_id, workspace_id)",
        to = "(id, user_id, workspace_id)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub journal_entries_1: BelongsTo<crate::entities::trading::journal_entries::Entity>,
    #[sea_orm(
        belongs_to,
        from = "companion_note_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub notebook_notes: BelongsTo<Option<crate::entities::notebook::notebook_notes::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "playbook_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub playbooks: BelongsTo<Option<crate::entities::trading::playbooks::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Workspaces2",
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces_2: BelongsTo<crate::entities::core::workspaces::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Workspaces1",
        from = "(workspace_id, user_id)",
        to = "(id, user_id)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces_1: BelongsTo<crate::entities::core::workspaces::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
