//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "journal_grouping_operations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub workspace_id: String,
    #[sea_orm(column_type = "Text")]
    pub kind: String,
    #[sea_orm(column_type = "Text")]
    pub state: String,
    pub source_revision: i64,
    pub grouping_revision: i64,
    #[sea_orm(column_type = "JsonBinary")]
    pub expected_versions: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub before_json: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub proposal_json: Json,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub after_json: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub undo_of: Option<String>,
    pub expires_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    pub committed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(has_many)]
    pub journal_grouping_feedbacks:
        HasMany<crate::entities::journal_flow::journal_grouping_feedback::Entity>,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "undo_of",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub journal_grouping_operations: BelongsTo<Option<Entity>>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Workspaces2",
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces_2: BelongsTo<crate::entities::core::workspaces::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Workspaces1",
        from = "(workspace_id, user_id)",
        to = "(id, user_id)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces_1: BelongsTo<crate::entities::core::workspaces::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
