//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "journal_grouping_suggestions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "journal_grouping_suggestions_user_id_workspace_id_candidate_key"
    )]
    pub user_id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "journal_grouping_suggestions_user_id_workspace_id_candidate_key"
    )]
    pub workspace_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub episode_id: Option<String>,
    pub source_revision: i64,
    #[sea_orm(
        column_type = "Text",
        unique_key = "journal_grouping_suggestions_user_id_workspace_id_candidate_key"
    )]
    pub candidate_key: String,
    #[sea_orm(column_type = "Text")]
    pub rule_version: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub proposal_json: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub features_json: Json,
    #[sea_orm(column_type = "Text")]
    pub explanation: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub journal_grouping_feedbacks:
        HasMany<crate::entities::journal_flow::journal_grouping_feedback::Entity>,
    #[sea_orm(
        belongs_to,
        from = "episode_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub trade_episodes: BelongsTo<Option<crate::entities::trading::trade_episodes::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Workspaces2",
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces_2: BelongsTo<crate::entities::core::workspaces::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Workspaces1",
        from = "(workspace_id, user_id)",
        to = "(id, user_id)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces_1: BelongsTo<crate::entities::core::workspaces::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
