//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "journal_projection_jobs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub workspace_id: String,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    pub requested_revision: i64,
    #[sea_orm(column_type = "Text")]
    pub state: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub lease_owner: Option<String>,
    pub lease_until: Option<DateTimeWithTimeZone>,
    pub attempt_count: i32,
    pub available_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error: Option<String>,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Workspaces2",
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces_2: BelongsTo<crate::entities::core::workspaces::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Workspaces1",
        from = "(workspace_id, user_id)",
        to = "(id, user_id)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces_1: BelongsTo<crate::entities::core::workspaces::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
