//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "journal_grouping_feedback")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub workspace_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub suggestion_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub operation_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub disposition: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub pattern_json: Json,
    pub recorded_at: DateTimeWithTimeZone,
    pub revoked_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        belongs_to,
        from = "operation_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub journal_grouping_operations:
        BelongsTo<Option<crate::entities::journal_flow::journal_grouping_operations::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "suggestion_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub journal_grouping_suggestions:
        BelongsTo<Option<crate::entities::journal_flow::journal_grouping_suggestions::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Workspaces2",
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces_2: BelongsTo<crate::entities::core::workspaces::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Workspaces1",
        from = "(workspace_id, user_id)",
        to = "(id, user_id)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces_1: BelongsTo<crate::entities::core::workspaces::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
