//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "journal_mutations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "journal_mutations_user_id_client_id_mutation_id_key"
    )]
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub workspace_id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "journal_mutations_user_id_client_id_mutation_id_key"
    )]
    pub client_id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "journal_mutations_user_id_client_id_mutation_id_key"
    )]
    pub mutation_id: String,
    #[sea_orm(column_type = "Text")]
    pub payload_hash: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub result_json: Json,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Workspaces2",
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces_2: BelongsTo<crate::entities::core::workspaces::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Workspaces1",
        from = "(workspace_id, user_id)",
        to = "(id, user_id)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces_1: BelongsTo<crate::entities::core::workspaces::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
