//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "journal_review_sessions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "journal_review_sessions_user_id_workspace_id_session_date_t_key"
    )]
    pub user_id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "journal_review_sessions_user_id_workspace_id_session_date_t_key"
    )]
    pub workspace_id: String,
    #[sea_orm(unique_key = "journal_review_sessions_user_id_workspace_id_session_date_t_key")]
    pub session_date: Date,
    #[sea_orm(
        column_type = "Text",
        unique_key = "journal_review_sessions_user_id_workspace_id_session_date_t_key"
    )]
    pub timezone: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub queue_json: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub completed_json: Json,
    #[sea_orm(column_type = "Text", nullable)]
    pub cursor_entry_id: Option<String>,
    pub record_version: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub journal_trade_reviews:
        HasMany<crate::entities::journal_flow::journal_trade_reviews::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Workspaces2",
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces_2: BelongsTo<crate::entities::core::workspaces::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Workspaces1",
        from = "(workspace_id, user_id)",
        to = "(id, user_id)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces_1: BelongsTo<crate::entities::core::workspaces::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
