//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "brokerage_episode_publications")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub episode_id: String,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub workspace_id: String,
    #[sea_orm(column_type = "Text", unique)]
    pub journal_entry_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub plan_id: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "journal_entry_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub journal_entries: BelongsTo<crate::entities::trading::journal_entries::Entity>,
    #[sea_orm(
        belongs_to,
        from = "plan_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub position_calculator_plans:
        BelongsTo<Option<crate::entities::calculator::position_calculator_plans::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "episode_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub trade_episodes: BelongsTo<crate::entities::trading::trade_episodes::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces: BelongsTo<crate::entities::core::workspaces::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
