//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "brokerage_holdings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "brokerage_holdings_user_id_account_id_symbol_key"
    )]
    pub user_id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "brokerage_holdings_user_id_account_id_symbol_key"
    )]
    pub workspace_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub snaptrade_symbol_id: Option<String>,
    #[sea_orm(
        column_type = "Text",
        unique_key = "brokerage_holdings_user_id_account_id_symbol_key"
    )]
    pub symbol: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub symbol_description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub raw_symbol: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub currency: String,
    #[sea_orm(column_type = "Double")]
    pub units: f64,
    #[sea_orm(column_type = "Double")]
    pub price: f64,
    #[sea_orm(column_type = "Double", nullable)]
    pub market_value: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub open_pnl: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub average_purchase_price: Option<f64>,
    pub is_option: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub option_type: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub strike_price: Option<f64>,
    pub expiration_date: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub raw_json: String,
    pub synced_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces: BelongsTo<crate::entities::core::workspaces::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
