//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "brokerage_sync_state")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub user_id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub workspace_id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub snaptrade_account_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub transactions_last_successful_sync: Option<String>,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub holdings_last_successful_sync: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub transaction_import_mode: Option<String>,
    pub transaction_import_start_date: Option<Date>,
    pub transaction_import_configured_at: Option<DateTimeWithTimeZone>,
    pub transaction_initial_import_completed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces: BelongsTo<crate::entities::core::workspaces::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
