//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "brokerage_transactions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", unique_key = "idx_brokerage_tx_dedup")]
    pub user_id: String,
    #[sea_orm(column_type = "Text", unique_key = "idx_brokerage_tx_dedup")]
    pub workspace_id: String,
    #[sea_orm(column_type = "Text")]
    pub snaptrade_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub symbol: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub symbol_description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub raw_symbol: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub currency: String,
    #[sea_orm(column_type = "Text")]
    pub transaction_type: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub option_type: Option<String>,
    #[sea_orm(column_type = "Double")]
    pub price: f64,
    #[sea_orm(column_type = "Double")]
    pub units: f64,
    #[sea_orm(column_type = "Double", nullable)]
    pub amount: Option<f64>,
    #[sea_orm(column_type = "Double")]
    pub fee: f64,
    #[sea_orm(column_type = "Double", nullable)]
    pub fx_rate: Option<f64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub trade_date: Option<DateTimeWithTimeZone>,
    pub settlement_date: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub institution: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub external_reference_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub raw_json: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Double")]
    pub contract_multiplier: f64,
    #[sea_orm(column_type = "Text", nullable)]
    pub underlying_symbol: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub option_kind: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub strike_price: Option<f64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub option_expiration: Option<String>,
    #[sea_orm(column_type = "Text", unique_key = "idx_brokerage_tx_dedup")]
    pub dedup_key: String,
    #[sea_orm(has_many)]
    pub trade_episode_fills: HasMany<crate::entities::trading::trade_episode_fills::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces: BelongsTo<crate::entities::core::workspaces::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
