//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "brokerage_connections")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub workspace_id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "idx_brokerage_connections_user_snaptrade_account"
    )]
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub provider: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub broker: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub snaptrade_user_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub snaptrade_user_secret_encrypted: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub snaptrade_connection_id: Option<String>,
    #[sea_orm(
        column_type = "Text",
        nullable,
        unique_key = "idx_brokerage_connections_user_snaptrade_account"
    )]
    pub snaptrade_account_id: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub total_value: Option<f64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub total_value_currency: Option<String>,
    pub connection_disabled: bool,
    pub connection_disabled_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub data_freshness_mode: String,
    #[sea_orm(column_type = "Text")]
    pub last_sync_status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_sync_error: Option<String>,
    pub last_sync_started_at: Option<DateTimeWithTimeZone>,
    pub last_sync_finished_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_sync_id: Option<String>,
    pub last_sync_succeeded_at: Option<DateTimeWithTimeZone>,
    pub last_sync_transactions_synced: i32,
    pub last_sync_holdings_synced: i32,
    pub last_sync_balances_synced: i32,
    pub setup_completed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub auth_mode: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub oauth_grant_id: Option<String>,
    #[sea_orm(
        belongs_to,
        from = "oauth_grant_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub snaptrade_oauth_grants:
        BelongsTo<Option<crate::entities::brokerage::snaptrade_oauth_grants::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Workspaces2",
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces_2: BelongsTo<crate::entities::core::workspaces::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
