//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "brokerage_balances")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "brokerage_balances_user_id_account_id_currency_key"
    )]
    pub user_id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "brokerage_balances_user_id_account_id_currency_key"
    )]
    pub workspace_id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "brokerage_balances_user_id_account_id_currency_key"
    )]
    pub currency: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub cash: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub buying_power: Option<f64>,
    pub synced_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces: BelongsTo<crate::entities::core::workspaces::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
