//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "brokerage_reconciliation_state")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub user_id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub workspace_id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub snaptrade_account_id: String,
    #[sea_orm(column_type = "Text")]
    pub diagnostic_id: String,
    #[sea_orm(column_type = "Text")]
    pub transaction_status: String,
    pub transaction_checked_at: Option<DateTimeWithTimeZone>,
    pub broker_transaction_count: i32,
    pub mapped_transaction_count: i32,
    pub imported_transaction_count: i32,
    pub duplicate_transaction_count: i32,
    pub skipped_transaction_count: i32,
    pub pending_transaction_count: i32,
    pub failed_transaction_count: i32,
    pub local_transaction_count: i32,
    pub missing_transaction_count: i32,
    pub extra_transaction_count: i32,
    #[sea_orm(column_type = "Text")]
    pub portfolio_status: String,
    pub portfolio_checked_at: Option<DateTimeWithTimeZone>,
    pub broker_holding_count: i32,
    pub mapped_holding_count: i32,
    pub local_holding_count: i32,
    pub broker_balance_count: i32,
    pub local_balance_count: i32,
    pub balance_discrepancy_count: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub transaction_error: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub portfolio_error: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub transaction_import_start_date: Option<Date>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
