//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "snaptrade_webhook_events")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub event_id: String,
    #[sea_orm(column_type = "Text")]
    pub event_type: String,
    #[sea_orm(column_type = "Text")]
    pub snaptrade_user_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub snaptrade_account_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub snaptrade_connection_id: Option<String>,
    pub event_timestamp: DateTimeWithTimeZone,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub details: Option<Json>,
    #[sea_orm(column_type = "JsonBinary")]
    pub normalized_event: Json,
    pub attempts: i32,
    pub next_attempt_at: DateTimeWithTimeZone,
    pub processed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub oauth_client_id: Option<String>,
}

impl ActiveModelBehavior for ActiveModel {}
