//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "snaptrade_oauth_grants")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "snaptrade_oauth_grants_user_client_unique"
    )]
    pub user_id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "snaptrade_oauth_grants_user_client_unique"
    )]
    pub oauth_client_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub snaptrade_user_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub access_token_encrypted: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub refresh_token_encrypted: Option<String>,
    pub access_token_expires_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = r#"custom("text[]")"#)]
    pub scopes: Vec<String>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub authorized_at: Option<DateTimeWithTimeZone>,
    pub last_refreshed_at: Option<DateTimeWithTimeZone>,
    pub revoked_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub brokerage_connections: HasMany<crate::entities::brokerage::brokerage_connections::Entity>,
    #[sea_orm(has_many)]
    pub snaptrade_oauth_attempts:
        HasMany<crate::entities::brokerage::snaptrade_oauth_attempts::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
