//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "plan_limits")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub plan: String,
    pub ai_actions_per_month: Option<i32>,
    pub brokerage_connections: Option<i32>,
    pub data_bytes: Option<i64>,
    pub media_bytes: Option<i64>,
    pub workspace_limit: Option<i32>,
    pub brokerage_history_days: Option<i32>,
    pub advanced_analytics: bool,
    pub universal_definitions: bool,
    pub mcp_access: bool,
    pub desktop_access: bool,
}

impl ActiveModelBehavior for ActiveModel {}
