//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", unique)]
    pub clerk_uuid: String,
    #[sea_orm(column_type = "Text")]
    pub full_name: String,
    #[sea_orm(column_type = "Text")]
    pub email: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub plan: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub paddle_customer_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub paddle_subscription_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub subscription_status: Option<String>,
    pub subscription_updated_at: Option<DateTimeWithTimeZone>,
    pub current_period_start: Option<DateTimeWithTimeZone>,
    pub current_period_end: Option<DateTimeWithTimeZone>,
    pub grace_until: Option<DateTimeWithTimeZone>,
    pub quota_anchor_day: Option<i16>,
    pub data_bytes_used: i64,
    pub media_bytes_used: i64,
    pub media_bytes_reserved: i64,
    pub usage_recomputed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub paddle_checkout_transaction_id: Option<String>,
    pub paddle_checkout_created_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub paddle_checkout_cadence: Option<String>,
    #[sea_orm(has_many)]
    pub agent_action_executions: HasMany<crate::entities::agents::agent_action_executions::Entity>,
    #[sea_orm(has_many)]
    pub agent_assistance_requests:
        HasMany<crate::entities::agents::agent_assistance_requests::Entity>,
    #[sea_orm(has_many)]
    pub agent_claims: HasMany<crate::entities::agents::agent_claims::Entity>,
    #[sea_orm(has_many)]
    pub agent_conversation_summary_jobs:
        HasMany<crate::entities::agents::agent_conversation_summary_jobs::Entity>,
    #[sea_orm(has_many)]
    pub agent_conversations: HasMany<crate::entities::agents::agent_conversations::Entity>,
    #[sea_orm(has_many)]
    pub agent_evidences: HasMany<crate::entities::agents::agent_evidence::Entity>,
    #[sea_orm(has_many)]
    pub agent_index_outboxes: HasMany<crate::entities::agents::agent_index_outbox::Entity>,
    #[sea_orm(has_many)]
    pub agent_memory_jobs: HasMany<crate::entities::agents::agent_memory_jobs::Entity>,
    #[sea_orm(has_many)]
    pub agent_messages: HasMany<crate::entities::agents::agent_messages::Entity>,
    #[sea_orm(has_many)]
    pub agent_run_events: HasMany<crate::entities::agents::agent_run_events::Entity>,
    #[sea_orm(has_many)]
    pub agent_run_items: HasMany<crate::entities::agents::agent_run_items::Entity>,
    #[sea_orm(has_many)]
    pub agent_runs: HasMany<crate::entities::agents::agent_runs::Entity>,
    #[sea_orm(has_many)]
    pub agent_tool_calls: HasMany<crate::entities::agents::agent_tool_calls::Entity>,
    #[sea_orm(has_many)]
    pub brokerage_balances: HasMany<crate::entities::brokerage::brokerage_balances::Entity>,
    #[sea_orm(has_many)]
    pub brokerage_connections: HasMany<crate::entities::brokerage::brokerage_connections::Entity>,
    #[sea_orm(has_many)]
    pub brokerage_data_reports: HasMany<crate::entities::brokerage::brokerage_data_reports::Entity>,
    #[sea_orm(has_many)]
    pub brokerage_episode_publications:
        HasMany<crate::entities::brokerage::brokerage_episode_publications::Entity>,
    #[sea_orm(has_many)]
    pub brokerage_holdings: HasMany<crate::entities::brokerage::brokerage_holdings::Entity>,
    #[sea_orm(has_many)]
    pub brokerage_reconciliation_states:
        HasMany<crate::entities::brokerage::brokerage_reconciliation_state::Entity>,
    #[sea_orm(has_many)]
    pub brokerage_sync_states: HasMany<crate::entities::brokerage::brokerage_sync_state::Entity>,
    #[sea_orm(has_many)]
    pub brokerage_transactions: HasMany<crate::entities::brokerage::brokerage_transactions::Entity>,
    #[sea_orm(has_one)]
    pub founder_grants: HasOne<crate::entities::core::founder_grants::Entity>,
    #[sea_orm(has_many)]
    pub journal_brokerage_links: HasMany<crate::entities::trading::journal_brokerage_links::Entity>,
    #[sea_orm(has_many)]
    pub journal_entries: HasMany<crate::entities::trading::journal_entries::Entity>,
    #[sea_orm(has_many)]
    pub manual_execution_claims: HasMany<crate::entities::trading::manual_execution_claims::Entity>,
    #[sea_orm(has_many)]
    pub notebook_client_mutations:
        HasMany<crate::entities::notebook::notebook_client_mutations::Entity>,
    #[sea_orm(has_many)]
    pub notebook_folders: HasMany<crate::entities::notebook::notebook_folders::Entity>,
    #[sea_orm(has_many)]
    pub notebook_images: HasMany<crate::entities::notebook::notebook_images::Entity>,
    #[sea_orm(has_many)]
    pub notebook_media_blobs: HasMany<crate::entities::notebook::notebook_media_blobs::Entity>,
    #[sea_orm(has_many)]
    pub notebook_media_outboxes: HasMany<crate::entities::notebook::notebook_media_outbox::Entity>,
    #[sea_orm(has_many)]
    pub notebook_media_references:
        HasMany<crate::entities::notebook::notebook_media_references::Entity>,
    #[sea_orm(has_many)]
    pub notebook_media_uploads: HasMany<crate::entities::notebook::notebook_media_uploads::Entity>,
    #[sea_orm(has_many)]
    pub notebook_notes: HasMany<crate::entities::notebook::notebook_notes::Entity>,
    #[sea_orm(has_many)]
    pub notification_outboxes: HasMany<crate::entities::notifications::notification_outbox::Entity>,
    #[sea_orm(has_many)]
    pub notification_preferences:
        HasMany<crate::entities::notifications::notification_preferences::Entity>,
    #[sea_orm(has_many)]
    pub notification_schedule_runs:
        HasMany<crate::entities::notifications::notification_schedule_runs::Entity>,
    #[sea_orm(has_one)]
    pub notification_user_settings:
        HasOne<crate::entities::notifications::notification_user_settings::Entity>,
    #[sea_orm(has_many)]
    pub notifications: HasMany<crate::entities::notifications::notification_records::Entity>,
    #[sea_orm(has_many)]
    pub playbooks: HasMany<crate::entities::trading::playbooks::Entity>,
    #[sea_orm(has_many)]
    pub position_calculator_histories:
        HasMany<crate::entities::calculator::position_calculator_history::Entity>,
    #[sea_orm(has_many)]
    pub position_calculator_plans:
        HasMany<crate::entities::calculator::position_calculator_plans::Entity>,
    #[sea_orm(has_many)]
    pub position_calculator_rules:
        HasMany<crate::entities::calculator::position_calculator_rules::Entity>,
    #[sea_orm(has_many)]
    pub push_subscriptions: HasMany<crate::entities::notifications::push_subscriptions::Entity>,
    #[sea_orm(has_many)]
    pub snaptrade_oauth_attempts:
        HasMany<crate::entities::brokerage::snaptrade_oauth_attempts::Entity>,
    #[sea_orm(has_many)]
    pub snaptrade_oauth_grants: HasMany<crate::entities::brokerage::snaptrade_oauth_grants::Entity>,
    #[sea_orm(has_one)]
    pub tag_categories: HasOne<crate::entities::trading::tag_categories::Entity>,
    #[sea_orm(has_many)]
    pub tags: HasMany<crate::entities::trading::tags::Entity>,
    #[sea_orm(has_many)]
    pub trade_episode_matches: HasMany<crate::entities::trading::trade_episode_matches::Entity>,
    #[sea_orm(has_many)]
    pub trade_episodes: HasMany<crate::entities::trading::trade_episodes::Entity>,
    #[sea_orm(has_many)]
    pub trade_review_versions: HasMany<crate::entities::trading::trade_review_versions::Entity>,
    #[sea_orm(has_many)]
    pub trading_principles: HasMany<crate::entities::trading::trading_principles::Entity>,
    #[sea_orm(has_many)]
    pub usage_counters: HasMany<crate::entities::core::usage_counters::Entity>,
    #[sea_orm(has_many)]
    pub user_prompts: HasMany<crate::entities::core::user_prompts::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
