//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "workspaces")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        column_type = "Text",
        unique_key = "idx_workspaces_id_user"
    )]
    pub id: String,
    #[sea_orm(column_type = "Text", unique_key = "idx_workspaces_id_user")]
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub icon: String,
    #[sea_orm(column_type = "Text")]
    pub currency: String,
    #[sea_orm(column_type = "Text")]
    pub risk_profile: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub asset_class: String,
    #[sea_orm(has_many)]
    pub agent_action_executions: HasMany<crate::entities::agents::agent_action_executions::Entity>,
    #[sea_orm(has_many)]
    pub agent_action_proposals: HasMany<crate::entities::agents::agent_action_proposals::Entity>,
    #[sea_orm(has_many)]
    pub agent_claims: HasMany<crate::entities::agents::agent_claims::Entity>,
    #[sea_orm(has_many)]
    pub agent_conversation_summary_jobs:
        HasMany<crate::entities::agents::agent_conversation_summary_jobs::Entity>,
    #[sea_orm(has_many)]
    pub agent_conversations: HasMany<crate::entities::agents::agent_conversations::Entity>,
    #[sea_orm(has_many)]
    pub agent_evidences: HasMany<crate::entities::agents::agent_evidence::Entity>,
    #[sea_orm(has_many)]
    pub agent_index_outboxes: HasMany<crate::entities::agents::agent_index_outbox::Entity>,
    #[sea_orm(has_many)]
    pub agent_memory_jobs: HasMany<crate::entities::agents::agent_memory_jobs::Entity>,
    #[sea_orm(has_many)]
    pub agent_messages: HasMany<crate::entities::agents::agent_messages::Entity>,
    #[sea_orm(has_many)]
    pub agent_run_events: HasMany<crate::entities::agents::agent_run_events::Entity>,
    #[sea_orm(has_many)]
    pub agent_run_items: HasMany<crate::entities::agents::agent_run_items::Entity>,
    #[sea_orm(has_many)]
    pub agent_runs: HasMany<crate::entities::agents::agent_runs::Entity>,
    #[sea_orm(has_many)]
    pub agent_tool_calls: HasMany<crate::entities::agents::agent_tool_calls::Entity>,
    #[sea_orm(has_many)]
    pub brokerage_balances: HasMany<crate::entities::brokerage::brokerage_balances::Entity>,
    #[sea_orm(has_many)]
    pub brokerage_episode_publications:
        HasMany<crate::entities::brokerage::brokerage_episode_publications::Entity>,
    #[sea_orm(has_many)]
    pub brokerage_holdings: HasMany<crate::entities::brokerage::brokerage_holdings::Entity>,
    #[sea_orm(has_many)]
    pub brokerage_sync_states: HasMany<crate::entities::brokerage::brokerage_sync_state::Entity>,
    #[sea_orm(has_many)]
    pub brokerage_transactions: HasMany<crate::entities::brokerage::brokerage_transactions::Entity>,
    #[sea_orm(has_many)]
    pub journal_entries: HasMany<crate::entities::trading::journal_entries::Entity>,
    #[sea_orm(has_many)]
    pub manual_execution_claims: HasMany<crate::entities::trading::manual_execution_claims::Entity>,
    #[sea_orm(has_one)]
    pub notebook_folders: HasOne<crate::entities::notebook::notebook_folders::Entity>,
    #[sea_orm(has_many)]
    pub notebook_media_references:
        HasMany<crate::entities::notebook::notebook_media_references::Entity>,
    #[sea_orm(has_many)]
    pub notebook_media_uploads: HasMany<crate::entities::notebook::notebook_media_uploads::Entity>,
    #[sea_orm(has_many)]
    pub notebook_notes: HasMany<crate::entities::notebook::notebook_notes::Entity>,
    #[sea_orm(has_many)]
    pub position_calculator_rules:
        HasMany<crate::entities::calculator::position_calculator_rules::Entity>,
    #[sea_orm(has_many)]
    pub snaptrade_oauth_attempts:
        HasMany<crate::entities::brokerage::snaptrade_oauth_attempts::Entity>,
    #[sea_orm(has_many)]
    pub trade_episode_matches: HasMany<crate::entities::trading::trade_episode_matches::Entity>,
    #[sea_orm(has_many)]
    pub trade_episodes: HasMany<crate::entities::trading::trade_episodes::Entity>,
    #[sea_orm(has_many)]
    pub trade_review_versions: HasMany<crate::entities::trading::trade_review_versions::Entity>,
    #[sea_orm(has_many)]
    pub trading_principles: HasMany<crate::entities::trading::trading_principles::Entity>,
    #[sea_orm(has_many, via = "playbook_workspace_applicability")]
    pub playbooks: HasMany<crate::entities::trading::playbooks::Entity>,
    #[sea_orm(has_many, via = "tag_category_workspace_applicability")]
    pub tag_categories: HasMany<crate::entities::trading::tag_categories::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
