//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "notification_deliveries")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub notification_id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub subscription_id: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub attempts: i32,
    pub next_attempt_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error: Option<String>,
    pub sent_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        belongs_to,
        from = "notification_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub notifications: BelongsTo<crate::entities::notifications::notification_records::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
