//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "notebook_images")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", unique_key = "ux_notebook_images_note_hash")]
    pub user_id: String,
    #[sea_orm(column_type = "Text", unique_key = "ux_notebook_images_note_hash")]
    pub note_id: String,
    #[sea_orm(column_type = "Text")]
    pub workspace_id: String,
    #[sea_orm(column_type = "Text")]
    pub cloudinary_asset_id: String,
    #[sea_orm(column_type = "Text")]
    pub cloudinary_public_id: String,
    #[sea_orm(column_type = "Text")]
    pub secure_url: String,
    pub width: i64,
    pub height: i64,
    #[sea_orm(column_type = "Text")]
    pub format: String,
    pub bytes: i64,
    #[sea_orm(column_type = "Text")]
    pub original_filename: String,
    #[sea_orm(column_type = "Text")]
    pub media_type: String,
    #[sea_orm(column_type = "Text")]
    pub content_type: String,
    #[sea_orm(column_type = "Double")]
    pub duration_seconds: f64,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", unique_key = "ux_notebook_images_note_hash")]
    pub content_hash: String,
    #[sea_orm(
        belongs_to,
        from = "note_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub notebook_notes: BelongsTo<crate::entities::notebook::notebook_notes::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces: BelongsTo<crate::entities::core::workspaces::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
