//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "notebook_media_blobs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub content_hash: Option<String>,
    #[sea_orm(column_type = "Text", unique)]
    pub object_key: String,
    #[sea_orm(column_type = "Text")]
    pub state: String,
    #[sea_orm(column_type = "Text")]
    pub content_type: String,
    #[sea_orm(column_type = "Text")]
    pub media_type: String,
    #[sea_orm(column_type = "Text")]
    pub format: String,
    pub bytes: i64,
    pub width: i64,
    pub height: i64,
    #[sea_orm(column_type = "Double")]
    pub duration_seconds: f64,
    #[sea_orm(column_type = "Text")]
    pub checksum_sha256: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub etag: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub derivative_key: Option<String>,
    pub derivative_bytes: i64,
    pub quota_counted: bool,
    pub upload_expires_at: Option<DateTimeWithTimeZone>,
    pub delete_after: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub lease_owner: Option<String>,
    pub leased_at: Option<DateTimeWithTimeZone>,
    pub attempt_count: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error_code: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub notebook_media_outboxes: HasMany<crate::entities::notebook::notebook_media_outbox::Entity>,
    #[sea_orm(has_many)]
    pub notebook_media_references:
        HasMany<crate::entities::notebook::notebook_media_references::Entity>,
    #[sea_orm(has_many)]
    pub notebook_media_uploads: HasMany<crate::entities::notebook::notebook_media_uploads::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
