//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "notebook_note_trades")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub note_id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub trade_id: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "trade_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub journal_entries: BelongsTo<crate::entities::trading::journal_entries::Entity>,
    #[sea_orm(
        belongs_to,
        from = "note_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub notebook_notes: BelongsTo<crate::entities::notebook::notebook_notes::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
