//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "notebook_notes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub workspace_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub folder_id: Option<String>,
    pub sort_order: i64,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub document_json: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub hlc: String,
    pub is_starred: bool,
    pub is_pinned: bool,
    #[sea_orm(column_type = "Text")]
    pub purpose: String,
    #[sea_orm(
        belongs_to,
        from = "folder_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub notebook_folders: BelongsTo<Option<crate::entities::notebook::notebook_folders::Entity>>,
    #[sea_orm(has_many)]
    pub notebook_media_references:
        HasMany<crate::entities::notebook::notebook_media_references::Entity>,
    #[sea_orm(has_many)]
    pub notebook_media_uploads: HasMany<crate::entities::notebook::notebook_media_uploads::Entity>,
    #[sea_orm(has_one)]
    pub notebook_note_crdt: HasOne<crate::entities::notebook::notebook_note_crdt::Entity>,
    #[sea_orm(has_many)]
    pub notebook_note_updates: HasMany<crate::entities::notebook::notebook_note_updates::Entity>,
    #[sea_orm(has_many)]
    pub trading_principles: HasMany<crate::entities::trading::trading_principles::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces: BelongsTo<crate::entities::core::workspaces::Entity>,
    #[sea_orm(has_many, via = "notebook_note_trades")]
    pub journal_entries: HasMany<crate::entities::trading::journal_entries::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
