//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "notebook_note_updates")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub note_id: String,
    #[sea_orm(primary_key)]
    pub seq: i64,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub update: Vec<u8>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "note_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub notebook_notes: BelongsTo<crate::entities::notebook::notebook_notes::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
