//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "notebook_media_uploads")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub blob_id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "notebook_media_uploads_user_idempotency_key"
    )]
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub workspace_id: String,
    #[sea_orm(column_type = "Text")]
    pub note_id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "notebook_media_uploads_user_idempotency_key"
    )]
    pub idempotency_key: String,
    #[sea_orm(column_type = "Text")]
    pub expected_hash: String,
    pub expected_bytes: i64,
    pub reserved_bytes: i64,
    #[sea_orm(column_type = "Text")]
    pub content_type: String,
    #[sea_orm(column_type = "Text")]
    pub original_filename: String,
    #[sea_orm(column_type = "Text")]
    pub state: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub multipart_upload_id: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub multipart_parts: Json,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_code: Option<String>,
    pub expires_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub completed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        belongs_to,
        from = "blob_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub notebook_media_blobs: BelongsTo<crate::entities::notebook::notebook_media_blobs::Entity>,
    #[sea_orm(
        belongs_to,
        from = "note_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub notebook_notes: BelongsTo<crate::entities::notebook::notebook_notes::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces: BelongsTo<crate::entities::core::workspaces::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
