package services

import (
	"fmt"
	"strconv"

	"github.com/Johnson-f/tradistry_backend/models"
	"github.com/gofiber/fiber/v2"
)

// UserService handles user business logic
type UserService struct {
	// In a real application, this would include database connection
	// For now, we'll use mock data
}

// NewUserService creates a new user service instance
func NewUserService() *UserService {
	return &UserService{}
}

// CreateUser creates a new user
func (us *UserService) CreateUser(c *fiber.Ctx) error {
	var req models.UserCreateRequest
	
	if err := c.BodyParser(&req); err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{
			"error": "Invalid request body",
		})
	}

	// Mock user creation - in real app, save to database
	user := models.UserResponse{
		ID:        1, // This would be generated by database
		Email:     req.Email,
		Username:  req.Username,
		FirstName: req.FirstName,
		LastName:  req.LastName,
	}

	return c.Status(fiber.StatusCreated).JSON(fiber.Map{
		"message": "User created successfully",
		"user":    user,
	})
}

// GetUsers retrieves all users
func (us *UserService) GetUsers(c *fiber.Ctx) error {
	// Mock data - in real app, fetch from database
	users := []models.UserResponse{
		{
			ID:        1,
			Email:     "john@example.com",
			Username:  "john_trader",
			FirstName: "John",
			LastName:  "Doe",
		},
		{
			ID:        2,
			Email:     "jane@example.com",
			Username:  "jane_trader",
			FirstName: "Jane",
			LastName:  "Smith",
		},
	}

	return c.JSON(fiber.Map{
		"users": users,
		"count": len(users),
	})
}

// getUserIDFromContext extracts user ID from fiber context
func (s *UserService) getUserIDFromContext(c *fiber.Ctx) (string, error) {
	userID, ok := c.Locals("userID").(string)
	if !ok || userID == "" {
		return "", fmt.Errorf("user ID not found in context")
	}
	return userID, nil
}

// GetUserHandler handles GET /users/:id
func (s *UserService) GetUserHandler(c *fiber.Ctx) error {
	id, err := strconv.Atoi(c.Params("id"))
	if err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{
			"error": "Invalid user ID",
		})
	}

	// Get authenticated user ID from context
	authUserID, err := s.getUserIDFromContext(c)
	if err != nil {
		return c.Status(fiber.StatusUnauthorized).JSON(fiber.Map{
			"error": "Authentication required",
		})
	}

	// Check if user is requesting their own data or has admin privileges
	if strconv.Itoa(id) != authUserID {
		// In a real app, check if user has admin role
		return c.Status(fiber.StatusForbidden).JSON(fiber.Map{
			"error": "Access denied",
		})
	}

	// Mock user - in real app, fetch from database
	user := models.UserResponse{
		ID:        int64(id),
		Email:     "user@example.com",
		Username:  "testuser",
		FirstName: "Test",
		LastName:  "User",
	}

	return c.JSON(user)
}

// UpdateUserHandler handles PUT /users/:id
func (s *UserService) UpdateUserHandler(c *fiber.Ctx) error {
	id, err := strconv.Atoi(c.Params("id"))
	if err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{
			"error": "Invalid user ID",
		})
	}

	// Get authenticated user ID from context
	authUserID, err := s.getUserIDFromContext(c)
	if err != nil {
		return c.Status(fiber.StatusUnauthorized).JSON(fiber.Map{
			"error": "Authentication required",
		})
	}

	// Check if user is updating their own data
	if strconv.Itoa(id) != authUserID {
		return c.Status(fiber.StatusForbidden).JSON(fiber.Map{
			"error": "Access denied",
		})
	}

	var req models.UserCreateRequest
	if err := c.BodyParser(&req); err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{
			"error": "Invalid request body",
		})
	}

	// Mock update - in real app, update in database
	user := models.UserResponse{
		ID:        int64(id),
		Email:     req.Email,
		Username:  req.Username,
		FirstName: req.FirstName,
		LastName:  req.LastName,
	}

	return c.JSON(fiber.Map{
		"message": "User updated successfully",
		"user":    user,
	})
}

// DeleteUserHandler handles DELETE /users/:id
func (s *UserService) DeleteUserHandler(c *fiber.Ctx) error {
	id, err := strconv.Atoi(c.Params("id"))
	if err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{
			"error": "Invalid user ID",
		})
	}

	// Get authenticated user ID from context
	authUserID, err := s.getUserIDFromContext(c)
	if err != nil {
		return c.Status(fiber.StatusUnauthorized).JSON(fiber.Map{
			"error": "Authentication required",
		})
	}

	// Check if user is deleting their own account
	if strconv.Itoa(id) != authUserID {
		return c.Status(fiber.StatusForbidden).JSON(fiber.Map{
			"error": "Access denied",
		})
	}

	// Mock deletion - in real app, delete from database
	return c.JSON(fiber.Map{
		"message": fmt.Sprintf("User %d deleted successfully", id),
	})
}
