//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.2

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "position_calculator_history")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub symbol: String,
    #[sea_orm(column_type = "Text")]
    pub position_type: String,
    #[sea_orm(column_type = "Double")]
    pub entry_price: f64,
    #[sea_orm(column_type = "Double")]
    pub stop_loss: f64,
    #[sea_orm(column_type = "Double")]
    pub account_balance: f64,
    #[sea_orm(column_type = "Double")]
    pub account_risk: f64,
    #[sea_orm(column_type = "Double")]
    pub shares: f64,
    #[sea_orm(column_type = "Double")]
    pub position_value: f64,
    #[sea_orm(column_type = "Double")]
    pub account_pct: f64,
    #[sea_orm(column_type = "Double")]
    pub stop_loss_pct: f64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub hlc: String,
    #[sea_orm(column_type = "Text")]
    pub workspace_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub plan_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub tranches_json: String,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<crate::entities::core::users::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Workspaces2",
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces_2: BelongsTo<crate::entities::core::workspaces::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
